# Stage 1: Build
FROM node:18-alpine AS builder

# Installiere Abhängigkeiten
WORKDIR /app/frontend
COPY livinglabdashboard/package*.json ./
RUN npm install --registry=https://registry.npmjs.org

# Kopiere den gesamten Frontend-Code
COPY livinglabdashboard/ ./

# Führe den Build-Prozess aus
RUN npx nuxt build

# Stage 2: Run
FROM node:18-alpine

# Installiere PM2
RUN npm install -g pm2

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die gebauten Dateien aus dem Builder-Stage
COPY --from=builder /app/frontend/.nuxt /app/frontend/.nuxt
COPY --from=builder /app/frontend/package*.json /app/frontend/

# Installiere nur Produktionsabhängigkeiten
RUN cd frontend && npm install --only=production --registry=https://registry.npmjs.org

# Kopiere die PM2-Konfigurationsdatei
COPY ecosystem.config.js ./ecosystem.config.js

# Exponiere den benötigten Port
EXPOSE 3001

# Starte PM2, um die Anwendung zu starten
CMD ["pm2-runtime", "ecosystem.config.js"]
