version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lukasmetzler
      POSTGRES_DB: EVI
      POSTGRES_PASSWORD: "lukasmetzler"
      POSTGRES_OPTIONS: "-c search_path=evi"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  kafka:
    build: ./kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: wurstmeister/zookeeper

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
