version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lukasmetzler
      POSTGRES_DB: EVI
      POSTGRES_PASSWORD: "lukasmetzler"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    build: ./kafka
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./grafana-config:/etc/grafana

volumes:
  postgres-data:
