version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper_new
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper_new:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_new
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_new:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper_new:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka_new -Dcom.sun.management.jmxremote.rmi.port=9999"
    depends_on:
      - zookeeper
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres_new
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_new
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./defaults.ini:/etc/grafana/grafana.ini
    depends_on:
      - postgres
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - backend

  frontend:
    image: node:latest
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    networks:
      - backend

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop_new
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka_new:9092"
    depends_on:
      - kafka
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local

networks:
  backend:
    driver: bridge
