# Dockerfile-livinglab

# Basis-Image
FROM node:18-alpine

# Installiere PM2
RUN npm install -g pm2

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Erstelle Frontend und Backend Verzeichnisse im Container
RUN mkdir frontend

# Kopiere package.json und package-lock.json für Frontend
COPY livinglabdashboard/package*.json ./frontend/

# Setze NPM-Registry auf das Standard-Registry, um lokale Registry-Probleme zu vermeiden
RUN npm config set registry https://registry.npmjs.org

# Installiere Abhängigkeiten für Frontend mit expliziter Registry
RUN cd frontend && npm install --registry=https://registry.npmjs.org

# Kopiere den Frontend-Code (ohne den server-Ordner)
COPY livinglabdashboard/ ./frontend/
COPY livinglabdashboard/assets ./frontend/assets
COPY livinglabdashboard/components ./frontend/components
COPY livinglabdashboard/images ./frontend/images
COPY livinglabdashboard/layouts ./frontend/layouts
COPY livinglabdashboard/middleware ./frontend/middleware
COPY livinglabdashboard/nuxt.config.js ./frontend/
COPY livinglabdashboard/pages ./frontend/pages
COPY livinglabdashboard/plugins ./frontend/plugins
COPY livinglabdashboard/static ./frontend/static
COPY livinglabdashboard/store ./frontend/store
COPY livinglabdashboard/server/ ./frontend/server


# Kopiere die PM2-Konfigurationsdatei
COPY ecosystem.config.js ./ecosystem.config.js

# Exponiere die benötigten Ports
EXPOSE 3001

# Starte PM2, um sowohl Frontend als auch Backend zu starten
CMD ["pm2-runtime", "ecosystem.config.js"]
