version: "3"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lukasmetzler
      POSTGRES_DB: EVI
      POSTGRES_PASSWORD: "lukasmetzler"

  kafka:
    build: ./kafka
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
