global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka-server"
    static_configs:
      - targets: ["kafka:9092"]
  - job_name: "zookeeper-server"
    static_configs:
      - targets: ["zookeeper:2181"]
