apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: node:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: frontend-source
              mountPath: /app
          command: ["npm", "start"]
      volumes:
        - name: frontend-source
          hostPath:
            path: /path/to/your/frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
