{
 "title": "1.OG Raum 1 / 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blickrichtung Arbeitsplatz 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_roll_1 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Kopfposition Arbeitsplatz 1",
   "type": "grafana-xyzchart-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_x_1, headpose_y_1, headpose_z_1 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_pitch_1 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_yaw_1 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_roll_2 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Kopfposition Arbeitsplatz 2",
   "type": "grafana-xyzchart-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_x_2, headpose_y_2, headpose_z_2 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_pitch_2 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_yaw_2 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  }
 ]
}