{
 "title": "1.OG Raum 5",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Beleuchtung",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,light1_act_1og_r5 FROM dim_raffstore_light_data_1og_r5 drld5 JOIN fact_raffstore_light_facts frlf ON drld5.raffstore_light_data_1og_r5_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  },
  {
   "title": "Raffstore Süd",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,slat_ang1_act_1og_r5,slat_pos1_act_1og_r5 FROM dim_raffstore_light_data_1og_r5 drld5 JOIN fact_raffstore_light_facts frlf ON drld5.raffstore_light_data_1og_r5_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  },
  {
   "title": "Raffstore Ost 1",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,slat_ang2_act_1og_r5,slat_pos2_act_1og_r5 FROM dim_raffstore_light_data_1og_r5 drld5 JOIN fact_raffstore_light_facts frlf ON drld5.raffstore_light_data_1og_r5_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  },
  {
   "title": "Raffstore Ost 2",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,slat_ang3_act_1og_r5,slat_pos3_act_1og_r5 FROM dim_raffstore_light_data_1og_r5 drld5 JOIN fact_raffstore_light_facts frlf ON drld5.raffstore_light_data_1og_r5_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  }
 ]
}