{
 "title": "1.OG Raum 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Beleuchtungsstärke Arbeitsplatz",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, illum_mp1_act, illum_mp2_act, illum_mp3_act, illum_mp4_act FROM dim_illumination_datapoints_1og_r1 did1 JOIN fact_environmental_data_facts fedf ON did1.illumination_datapoints_id = fedf.illumination_datapoints_id"
    }
   ]
  },
  {
   "title": "Raumtemperatur",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, mp1_req_room_temp FROM dim_user_input_mp1_1og_r1 duim1 JOIN fact_user_input_facts fuif ON duim1.user_input_mp1_id = fuif.user_input_mp1_id"
    }
   ]
  },
  {
   "title": "Raffstore Süd",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, slat_ang1_act_1og_r1, slat_pos1_act_1og_r1 FROM dim_raffstore_light_data_1og_r1 drld1 JOIN fact_raffstore_light_facts frlf ON drld1.raffstore_light_data_1og_r1_id = frlf.raffstore_light_data_1og_r1_id"
    }
   ]
  },
  {
   "title": "Beleuchtung",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, light1_act_1og_r1, light2_act_1og_r1 FROM dim_raffstore_light_data_1og_r1 drld1 JOIN fact_raffstore_light_facts frlf ON drld1.raffstore_light_data_1og_r1_id = frlf.raffstore_light_data_1og_r1_id"
    }
   ]
  }
 ]
}