{
 "title": "1.OG Raum 4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Beleuchtung",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,light1_act_1og_r4,light2_act_1og_r4 FROM dim_raffstore_light_data_1og_r4 drld4 JOIN fact_raffstore_light_facts frlf ON drld4.raffstore_light_data_1og_r4_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  },
  {
   "title": "Raffstore Süd 1",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,slat_ang1_act_1og_r4,slat_pos1_act_1og_r4 FROM dim_raffstore_light_data_1og_r4 drld4 JOIN fact_raffstore_light_facts frlf ON drld4.raffstore_light_data_1og_r4_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  },
  {
   "title": "Raffstore Süd 2",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,slat_ang2_act_1og_r4,slat_pos2_act_1og_r4 FROM dim_raffstore_light_data_1og_r4 drld4 JOIN fact_raffstore_light_facts frlf ON drld4.raffstore_light_data_1og_r4_id = frlf.raffstore_light_light_facts_id"
    }
   ]
  }
 ]
}