{
 "title": "1.OG Raum 1 / 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blickrichtung Arbeitsplatz 3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_roll_3 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Kopfposition Arbeitsplatz 3",
   "type": "grafana-xyzchart-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_x_3, headpose_y_3, headpose_z_3 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_pitch_3 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_yaw_3 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_roll_4 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Kopfposition Arbeitsplatz 4",
   "type": "grafana-xyzchart-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_x_4, headpose_y_4, headpose_z_4 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_pitch_4 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  },
  {
   "title": "Blickrichtung Arbeitsplatz 4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, headpose_yaw_4 FROM dim_head_positions_1og_r1 dhp1 JOIN fact_environmental_data_facts fedf ON dhp1.head_positions_id = fedf.head_positions_id"
    }
   ]
  }
 ]
}