# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the application files
COPY producer.py .
COPY config.py .
COPY column_names.py .
COPY fact_column_names.py .
COPY fact_db_operations.py .
COPY postgres.py .

# Set the entrypoint
ENTRYPOINT ["python", "producer.py"]
