FROM python:3.10-slim

WORKDIR /app

COPY producer.py /app
COPY config.py /app
COPY column_names.py /app
COPY requirements.txt /app

RUN pip install -r requirements.txt

CMD ["python", "producer.py"]
