FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die notwendigen Dateien
COPY create_tables.py /app/create_tables.py
COPY models.py /app/models.py
COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

# Führe das Skript aus
CMD ["python", "create_tables.py"]
