FROM python:3.10-slim

WORKDIR /app

COPY consumer.py /app
COPY config.py /app
COPY column_names.py /app
COPY fact_column_names.py /app
COPY fact_db_operations.py /app
COPY postgres.py /app
COPY models.py /app
COPY requirements.txt /app

RUN pip install -r requirements.txt

COPY startup/start_consumer.sh /start_consumer.sh
RUN chmod +x /start_consumer.sh

CMD ["/start_consumer.sh", "python", "consumer.py"]
