FROM python:3.10-slim

WORKDIR /app

COPY consumer.py /app
COPY config.py /app
COPY column_names.py /app
COPY fact_column_names.py /app
COPY fact_db_operations.py /app
COPY postgres.py /app
COPY requirements.txt /app

RUN pip install -r requirements.txt

CMD ["python", "consumer.py"]
